version: "2.0"
services:
  my_page_counter_app:
    image: "ungar/week1:${TAG}"
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - my_redis_container
  my_redis_container:
    image: redis
